# Generated by Django 5.0.6 on 2024-06-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Naukri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(unique=True)),
                ('company', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=255)),
                ('salary', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(max_length=255)),
                ('responsibility', models.TextField(blank=True, null=True)),
                ('posted_date', models.DateField()),
                ('descriptions', models.JSONField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('industry_type', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=255, null=True)),
                ('role_category', models.CharField(blank=True, max_length=255, null=True)),
                ('education_ug', models.CharField(blank=True, max_length=255, null=True)),
                ('education_pg', models.CharField(blank=True, max_length=255, null=True)),
                ('key_skills', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
