# Generated by Django 5.0.6 on 2024-06-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naukri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naukri',
            name='posted_date',
            field=models.CharField(max_length=10),
        ),
    ]
