# Generated by Django 5.0.6 on 2024-06-28 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naukri', '0002_alter_naukri_posted_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='naukri',
            name='department',
        ),
        migrations.RemoveField(
            model_name='naukri',
            name='descriptions',
        ),
        migrations.RemoveField(
            model_name='naukri',
            name='education_pg',
        ),
        migrations.RemoveField(
            model_name='naukri',
            name='education_ug',
        ),
        migrations.RemoveField(
            model_name='naukri',
            name='employment_type',
        ),
        migrations.RemoveField(
            model_name='naukri',
            name='industry_type',
        ),
        migrations.RemoveField(
            model_name='naukri',
            name='key_skills',
        ),
        migrations.RemoveField(
            model_name='naukri',
            name='responsibility',
        ),
        migrations.RemoveField(
            model_name='naukri',
            name='role',
        ),
        migrations.RemoveField(
            model_name='naukri',
            name='role_category',
        ),
    ]
