# Generated by Django 5.0.6 on 2024-06-28 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indeed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indeed',
            name='department',
        ),
        migrations.RemoveField(
            model_name='indeed',
            name='descriptions',
        ),
        migrations.RemoveField(
            model_name='indeed',
            name='education_pg',
        ),
        migrations.RemoveField(
            model_name='indeed',
            name='education_ug',
        ),
        migrations.RemoveField(
            model_name='indeed',
            name='employment_type',
        ),
        migrations.RemoveField(
            model_name='indeed',
            name='industry_type',
        ),
        migrations.RemoveField(
            model_name='indeed',
            name='key_skills',
        ),
        migrations.RemoveField(
            model_name='indeed',
            name='responsibility',
        ),
        migrations.RemoveField(
            model_name='indeed',
            name='role',
        ),
        migrations.RemoveField(
            model_name='indeed',
            name='role_category',
        ),
    ]
